### ISSUE TITLE
RITM0756412 (vs-code + git Problems with Workshops -> Ansible Windows Workshop)

### ISSUE THREAD

**Issue by ShaddGallegos** [ansible/workshops#976] opened 2020-09-16 21:48 UTC
##### SUMMARY

Workshops is skipping part of the git role 

##### ISSUE TYPE

 - Bug Report

##### EXTRA VARS FILE

```paste below
I have no extra vars this was in RHPDS
```

e.g. here is an example of an extra vars file we are looking for:
```
$ cat ~/Github/linklight/provisioner/seans_workshop.yml
---
ec2_region: us-east-1
ec2_name_prefix: seantest
student_total: 25
admin_password: ansible
create_login_page: true
```
for more information on the extra vars file please refer to: https://github.com/network-automation/linklight/blob/master/provisioner/README.md

##### ANSIBLE VERSION

```paste below
[student15@ansible-1 ~]$ ansible --version
ansible 2.9.13
  config file = /home/student15/.ansible.cfg
  configured module search path = ['/home/student15/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```paste below
 ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/student15/.ansible.cfg) = ['/home/student15/lab_inventory/hosts']
DEFAULT_STDOUT_CALLBACK(/home/student15/.ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/student15/.ansible.cfg) = 60
DEPRECATION_WARNINGS(/home/student15/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/student15/.ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/student15/.ansible.cfg) = 200
PERSISTENT_CONNECT_TIMEOUT(/home/student15/.ansible.cfg) = 200
RETRY_FILES_ENABLED(/home/student15/.ansible.cfg) = False

```

##### OS / ENVIRONMENT

Whatever RHPDS is using 

##### TOWER
 UNKNOWN

##### PLAYBOOK SHORT OUTPUT

```paste below
https://github.com/ansible/workshops/blob/devel/provisioner/roles/gitlab-client/tasks/main.yml
```

##### PLAYBOOK LONG OUTPUT

```paste below
It is in RHPDS 
```
Here is my simple fix
sudo ansible localhost -m include_role -a name=/tmp/workshops/provisioner/roles/gitlab-client -e "username=student15 admin_password=1gEVJhXiXnW0i5 ec2_name_prefix=e484.open workshop_dns_zone=redhat.com"

sudo chown -R student15:student15 /home/student15
sudo find /home/student15/windows-workshop/workshop_project/.git -type d | xargs chmod 755
sudo find /home/student15/windows-workshop/workshop_project/.git/objects -type f | xargs chmod 444
sudo find /home/student15/windows-workshop/workshop_project/.git -type f | grep -v /objects/ | xargs chmod 644
sudo git config --global user.name "student15"
sudo git push --set-upstream origin master
sudo reboot

**Comment by cloin** [comment] 2020-09-18 15:27
Confirmed this works on master of workshop repo

**Comment by cloin** [comment] 2020-09-18 15:55
This seems to be a problem with RHPDS not pulling updated code from this repo. Closing here since it's not an issue with this code.

**Closed by cloin** 2020-09-18 15:55 UTC
