### ISSUE TITLE
Error in Exercise 8: Understanding RBAC in Automation controller

### ISSUE THREAD

**Issue by carlosfparada** [ansible/workshops#1528] opened 2022-02-25 15:08 UTC
### Area

Ansible Network Automation Workshop

### Proposed Changes

Error in controller trying to add a new command option (one of the proposed extra excecises at the end)
TypeError: t.choices.split is not a function at nC (https://student1.8cb5.example.opentlc.com/static/js/main.9eb9518d.chunk.js:1:1074036) at Zo (https://student1.8cb5.example.opentlc.com/static/js/2.97c02134.chunk.js:2:1413653) at Cs (https://student1.8cb5.example.opentlc.com/static/js/2.97c02134.chunk.js:2:1459883) at vl (https://student1.8cb5.example.opentlc.com/static/js/2.97c02134.chunk.js:2:1452610) at ml (https://student1.8cb5.example.opentlc.com/static/js/2.97c02134.chunk.js:2:1452535) at sl (https://student1.8cb5.example.opentlc.com/static/js/2.97c02134.chunk.js:2:1449544) at https://student1.8cb5.example.opentlc.com/static/js/2.97c02134.chunk.js:2:1400915 at t.unstable_runWithPriority (https://student1.8cb5.example.opentlc.com/static/js/2.97c02134.chunk.js:2:1476316) at Vi (https://student1.8cb5.example.opentlc.com/static/js/2.97c02134.chunk.js:2:1400624) at Yi (https://student1.8cb5.example.opentlc.com/static/js/2.97c02134.chunk.js:2:1400860)

**Comment by IPvSean** [comment] 2022-02-25 15:25
@carlosfparada can you elaborate here?  Not understanding what the issue is?

**Comment by carlosfparada** [comment] 2022-02-25 16:05
At the end of excercise 8 there is a "bonus step" saying: "If time permits, log back in as the network-admin and add another show command you would like the operator to run. This will also help you see how the Admin Role of the network-admin user allows you to edit/update the job template.". When you try to add a new command to the list in the survey it fails and dxisplays the above error stack.

**Comment by IPvSean** [comment] 2022-02-25 21:45
this is fixed in latest release, unable to replicate, should go live next week

**Closed by IPvSean** 2022-02-25 21:45 UTC

**Comment by carlosfparada** [comment] 2022-02-28 09:37
OK!
