### ISSUE TITLE
Can't find ami for satellite

### ISSUE THREAD

**Issue by pseguel-redhat** [ansible/workshops#1780] opened 2022-08-18 13:52 UTC
### Problem Summary

When launching provision.yml, playbook can't find satellite AMI ID. 
Using AWS Blank Open Environment account. 

From AWS console and/or AWS CLI I can't find images of this owner ID (551178754270).

How can I add this image?

```
TASK [../roles/manage_ec2_instances : find ami for satellite] ****************************************************************************************************
(...)
ok: [localhost] => {
    "changed": false,
    "images": [],
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_ca_bundle": null,
            "aws_config": null,
            "aws_secret_key": null,
            "debug_botocore_endpoint_logs": false,
            "describe_image_attributes": false,
            "ec2_url": null,
            "executable_users": [],
            "filters": {
                "name": "Satellite*",
                "owner-id": [
                    "551178754270"
                ]
            },
            "image_ids": [],
            "owners": [
                "551178754270"
            ],
            "profile": null,
            "region": "us-east-1",
            "security_token": null,
            "validate_certs": true
        }
    }
}
```

### Issue Type

Bug

### Extra vars file

```
---
# region where the nodes will live
ec2_region: us-east-1
# name prefix for all the VMs
ec2_name_prefix: MIBANCOSAT
# amount of work benches to provision
student_total: 1
# workshop is put into rhel mode
workshop_type: smart_mgmt
# define DNS zone. AWS DNS required
dns_type: aws
# password used for student account on control node
admin_password: R3dh4t1!
# Required for AAP download https://access.redhat.com/articles/3626371
offline_token:  (REDACTED)
# Required for podman authentication to registry.redhat.io
redhat_username: (REDACTED)
redhat_password:  (REDACTED)
# DNS domain
workshop_dns_zone: "{{ lookup('env', 'AWS_DOMAIN') }}" 
## Optional Variables
# select rhel7 or rhel8 client nodes
rhel: rhel8
# this will install Automation controller on all control nodes
controllerinstall: false
pre_build: false
# this will install VS Code web on all control nodes
code_server: true
# this will change the location of lab guide
# ansible_workshops_url: https://github.com/ansible/workshops
# ansible_workshops_version: smart_mgmt
```

### Ansible Playbook Output

```
TASK [../roles/manage_ec2_instances : find ami for satellite] ****************************************************************************************************
task path: /Users/pauloseguel/Desktop/Ansible_Tests/satellite-wokshop/workshops/roles/manage_ec2_instances/tasks/ami_find/ami_find_smart_mgmt.yml:14
redirecting (type: modules) ansible.builtin.ec2_ami_info to amazon.aws.ec2_ami_info
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: pauloseguel
<127.0.0.1> EXEC /bin/sh -c 'echo ~pauloseguel && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/pauloseguel/.ansible/tmp `"&& mkdir "` echo /Users/pauloseguel/.ansible/tmp/ansible-tmp-1660827557.429033-71435-56050286295012 `" && echo ansible-tmp-1660827557.429033-71435-56050286295012="` echo /Users/pauloseguel/.ansible/tmp/ansible-tmp-1660827557.429033-71435-56050286295012 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.ec2_ami_info to amazon.aws.ec2_ami_info
Using module file /Users/pauloseguel/.ansible/collections/ansible_collections/amazon/aws/plugins/modules/ec2_ami_info.py
<127.0.0.1> PUT /Users/pauloseguel/.ansible/tmp/ansible-local-70502befro8qd/tmpj0ngj8a3 TO /Users/pauloseguel/.ansible/tmp/ansible-tmp-1660827557.429033-71435-56050286295012/AnsiballZ_ec2_ami_info.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/pauloseguel/.ansible/tmp/ansible-tmp-1660827557.429033-71435-56050286295012/ /Users/pauloseguel/.ansible/tmp/ansible-tmp-1660827557.429033-71435-56050286295012/AnsiballZ_ec2_ami_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/Users/pauloseguel/Desktop/Ansible_Tests/satellite-wokshop/workshops/provisioner/myenv/bin/python3 /Users/pauloseguel/.ansible/tmp/ansible-tmp-1660827557.429033-71435-56050286295012/AnsiballZ_ec2_ami_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/pauloseguel/.ansible/tmp/ansible-tmp-1660827557.429033-71435-56050286295012/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "changed": false,
    "images": [],
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_ca_bundle": null,
            "aws_config": null,
            "aws_secret_key": null,
            "debug_botocore_endpoint_logs": false,
            "describe_image_attributes": false,
            "ec2_url": null,
            "executable_users": [],
            "filters": {
                "name": "Satellite*",
                "owner-id": [
                    "551178754270"
                ]
            },
            "image_ids": [],
            "owners": [
                "551178754270"
            ],
            "profile": null,
            "region": "us-east-1",
            "security_token": null,
            "validate_certs": true
        }
    }
}

TASK [../roles/manage_ec2_instances : save ami for satellite] ****************************************************************************************************
task path: /Users/pauloseguel/Desktop/Ansible_Tests/satellite-wokshop/workshops/roles/manage_ec2_instances/tasks/ami_find/ami_find_smart_mgmt.yml:22
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: No last item, sequence was empty.\n\nThe error appears to be in '/Users/pauloseguel/Desktop/Ansible_Tests/satellite-wokshop/workshops/roles/manage_ec2_instances/tasks/ami_find/ami_find_smart_mgmt.yml': line 22, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: save ami for satellite\n  ^ here\n"
}

PLAY RECAP *******************************************************************************************************************************************************
localhost                  : ok=62   changed=18   unreachable=0    failed=1    skipped=21   rescued=0    ignored=0
```

### Ansible Version

```
ansible --version
/Users/pauloseguel/Desktop/Ansible_Tests/satellite-wokshop/workshops/provisioner/myenv/lib/python3.9/site-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
ansible [core 2.13.3]
  config file = /Users/pauloseguel/Desktop/Ansible_Tests/satellite-wokshop/workshops/provisioner/ansible.cfg
  configured module search path = ['/Users/pauloseguel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/pauloseguel/Desktop/Ansible_Tests/satellite-wokshop/workshops/provisioner/myenv/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/pauloseguel/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/pauloseguel/Desktop/Ansible_Tests/satellite-wokshop/workshops/provisioner/myenv/bin/ansible
  python version = 3.9.12 (main, Apr  5 2022, 01:53:17) [Clang 12.0.0 ]
  jinja version = 3.1.2
  libyaml = True
```

### Ansible Configuration

```
DEFAULT_FORKS(/Users/pauloseguel/Desktop/Ansible_Tests/satellite-wokshop/workshops/provisioner/ansible.cfg) = 50
DEFAULT_HOST_LIST(/Users/pauloseguel/Desktop/Ansible_Tests/satellite-wokshop/workshops/provisioner/ansible.cfg) = ['/Users/pauloseguel/Desktop/Ansible_Tests/satellite-wokshop/workshops/provisioner/hosts']
HOST_KEY_CHECKING(/Users/pauloseguel/Desktop/Ansible_Tests/satellite-wokshop/workshops/provisioner/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/Users/pauloseguel/Desktop/Ansible_Tests/satellite-wokshop/workshops/provisioner/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/Users/pauloseguel/Desktop/Ansible_Tests/satellite-wokshop/workshops/provisioner/ansible.cfg) = 60
RETRY_FILES_ENABLED(/Users/pauloseguel/Desktop/Ansible_Tests/satellite-wokshop/workshops/provisioner/ansible.cfg) = False
```

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

MacOS 12.5 using a virtualenv with requirements.txt of this repo applied

**Comment by IPvSean** [comment] 2022-08-29 15:14
duplicate of https://github.com/ansible/workshops/issues/1778

**Closed by IPvSean** 2022-08-29 15:14 UTC
