### ISSUE TITLE
Bug report for rhel_90 workshop module 6, step 4

### ISSUE THREAD

**Issue by hightechrdn** [ansible/workshops#1789] opened 2022-08-31 00:22 UTC
### Problem Summary

The AAP configuration deployed by RHPDS does not match the Ansible Red Hat Enterprise Linux Workshop (90 minute version) instructions- module 6, step 4

The credential "Workshop Credential" is not associated with the Job Template "SECURITY / Hardening", causing execution of the Job Template to fail. The credential "Workshop Credential" must be added to the "SECURITY / Hardening" Job Template.

### Issue Type

Bug

### Extra vars file

{
  "harden_firewall": "Yes",
  "harden_time": "Yes",
  "harden_ssh": "No",
  "harden_pci": "No"
}

### Ansible Playbook Output

PLAY [harden linux systems] ****************************************************
TASK [Gathering Facts] *********************************************************
fatal: [node1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '18.221.5.240' (ECDSA) to the list of known hosts.\r\nroot@18.221.5.240: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).", "unreachable": true}
fatal: [node2]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '18.188.124.216' (ECDSA) to the list of known hosts.\r\nroot@18.188.124.216: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).", "unreachable": true}
fatal: [node3]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '18.119.161.153' (ECDSA) to the list of known hosts.\r\nroot@18.119.161.153: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).", "unreachable": true}
PLAY RECAP *********************************************************************
node1                      : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
node2                      : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
node3                      : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0 

### Ansible Version

rhel_90 workshop execution environment

### Ansible Configuration

rhel_90 workshop execution environment

### Ansible Execution Node

Ansible Controller (previously known as Ansible Tower)

### Operating System

rhel_90 workshop execution environment

**Comment by IPvSean** [comment] 2023-10-06 16:06
duplicate of https://github.com/ansible/workshops/issues/1728

**Closed by IPvSean** 2023-10-06 16:06 UTC
