### ISSUE TITLE
AAP2 workshops fail to provision when automation_hub is undefined or false

### ISSUE THREAD

**Issue by 9strands** [ansible/workshops#1599] opened 2022-03-23 23:34 UTC
### Problem Summary

If automation_hub is "false" then, the  entry here is not created:

https://github.com/ansible/workshops/blob/578c89017559092a3594dcefd285a1c362692557/roles/manage_ec2_instances/templates/instructor_inventory/instructor_inventory_rhel.j2#L73

And when this https://github.com/ansible/workshops/blob/edaa98477ec064a92de48f4613d7c98a794ed765/roles/manage_ec2_instances/tasks/inventory/addhost_automation_hub.yml is called, then we receive the error 

fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'automation_hub_host_facts' is undefined"}

### Issue Type

Bug

### Extra vars file

N/A Deployment from RHPDS fails with variable "automation_hub" set as false or undefined "

### Ansible Playbook Output

fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'automation_hub_host_facts' is undefined"}

### Ansible Version

AAP2 workshop deployment in RHPDS with student workload rhel_tower_workshop

### Ansible Configuration

AAP2 workshop deployment in RHPDS with student workload rhel_tower_workshop

### Ansible Execution Node

Ansible Controller (previously known as Ansible Tower)

### Operating System

AAP2 workshop deployment in RHPDS with student workload rhel_tower_workshop

**Comment by IPvSean** [comment] 2022-03-24 12:46
I think the problem is actually you passed automation_hub as a string... I need to force inputs into a boolean

**Comment by IPvSean** [comment] 2022-03-24 13:05
this has been merged into `main`

**Closed by IPvSean** 2022-03-24 13:05 UTC
Labels: bug
