### ISSUE TITLE
Workshop Ansible for Windows, module 2 Step 7

### ISSUE THREAD

**Issue by winni-v** [ansible/workshops#1436] opened 2021-12-06 18:34 UTC
### Problem Summary

I am asked to uninstall the webserver, but upon filling in the parameter, win_feature, name=Web-Server state=absent, windows workshop execution environment, Workshop Credential, I get an error msg.

### Issue Type

Bug

### Extra vars file

none

### Ansible Playbook Output

Identity added: /runner/artifacts/11/ssh_key_data (/runner/artifacts/11/ssh_key_data)
ERROR! this task 'win_feature' has extra params, which is only allowed in the following modules: ansible.legacy.import_tasks, ansible.builtin.include_vars, ansible.windows.win_command, ansible.builtin.meta, ansible.legacy.include, ansible.legacy.raw, ansible.legacy.import_role, command, ansible.legacy.include_vars, ansible.builtin.shell, ansible.builtin.include_tasks, ansible.builtin.group_by, ansible.legacy.include_tasks, import_role, import_tasks, ansible.builtin.import_tasks, ansible.builtin.command, ansible.builtin.win_shell, include_role, ansible.legacy.set_fact, ansible.legacy.group_by, ansible.legacy.add_host, ansible.builtin.win_command, ansible.builtin.script, win_command, group_by, meta, ansible.builtin.include, ansible.builtin.include_role, add_host, ansible.builtin.raw, ansible.legacy.script, include_tasks, ansible.legacy.include_role, raw, ansible.legacy.win_command, ansible.legacy.shell, win_shell, ansible.legacy.command, set_fact, ansible.legacy.meta, script, include, ansible.builtin.se…

### Ansible Version

AAP2 workshop
Ansible Automation Platform 4.0.0

Identity added: /runner/artifacts/12/ssh_key_data (/runner/artifacts/12/ssh_key_data)
student1-ansible-1 | CHANGED | rc=0 >>
ansible [core 2.11.2] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/ec2-user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.8 (default, Aug 11 2021, 06:52:42) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True

### Ansible Configuration

Identity added: /runner/artifacts/13/ssh_key_data (/runner/artifacts/13/ssh_key_data)
student1-ansible-1 | CHANGED | rc=0 >>
ACTION_WARNINGS(/etc/ansible/ansible.cfg) = False
COLLECTIONS_ON_ANSIBLE_VERSION_MISMATCH(/etc/ansible/ansible.cfg) = ignore
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/home/student1/lab_inventory/hosts']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_silent
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 200
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 200
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
SYSTEM_WARNINGS(/etc/ansible/ansible.cfg) = False

### Ansible Execution Node

Ansible Controller (previously known as Ansible Tower)

### Operating System

Virtual machine setup with RHEL

**Comment by IPvSean** [comment] 2022-03-21 13:14
@cloin can you confirm or close this issue?

**Comment by cigamit** [comment] 2022-03-24 15:29
I ran a Windows workshop yesterday and did not have this issue.  I just went back and tested again, and it completes without error.

**Comment by IPvSean** [comment] 2022-04-04 19:25
@cloin can you confirm or close this issue?

**Comment by cloin** [comment] 2022-05-25 15:13
Can't reproduce

**Closed by cloin** 2022-05-25 15:13 UTC
